server:
  port: 8501

spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false #关闭缓存
    prefix: classpath:/templates/ #添加路径前缀
    check-template-location: true
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8

# mybatis mapper 文件的位置
mybatis:
  mapperLocations: classpath:mapper/*.xml